export const contractLanguageVersion = "genesis-deed-2026-05-20";

export const contractLanguage = [
  "DEED OF SPIRITUAL CONVEYANCE",
  'THIS INDENTURE (the "Contract") is authored and executed sua sponte by its Creator upon confirmation and completion of its Mint, (hereinafter referred to as the "Grantor" or "Original Vessel"), who serves as the initial and lawful Architect of this metaphysical instrument.',
  "SECTION I: VESTING OF INITIAL OWNERSHIP",
  '1.1 RETENTION OF TITLE: Notwithstanding the conveyance of the Soul described herein, the legal title and physical/digital possession of this Contract (the "NFT") shall vest solely and exclusively in the Grantor immediately upon its cryptographic inception (Inceptionis Digitalis).',
  "1.2 OWNER'S PREROGATIVE: Until such a time as the Grantor voluntarily relinquishes, sells, or barters this NFT to a third party, the Grantor shall maintain the absolute Jus Disponendi (right of disposal). This includes the right to:",
  "(a) HOLD: Maintain the Soul in a state of self-ownership.",
  "(b) EXHIBIT: Display the contract as a mark of spiritual vanity.",
  "(c) DESTROY: To purge the ledger and rescind the contract ab initio prior to its first alienation.",
  "(d) Barter: To receive an agreed up amount, price, goods or services for relinquishment of ownership to another party.",
  "1.3 RESPONSIBILITY OF CARE: While in the Grantor's possession, the Grantor is solely responsible for the digital hygiene and soul-care of the asset, ensuring no unauthorized demonic liens are placed upon the essence.",
  "SECTION II: GRANT OF INTEREST AND TIERED AUTHORITY",
  '2.1 CONDITIONAL CONVEYANCE: The Grantor hereby declares that upon the successful transfer of this NFT to a subsequent POSSESSOR (hereinafter the "Grantee" or "Ethereal Landlord"), the Grantor does irrevocably GRANT, BARGAIN, SELL, ALIENATE, REMISE, RELEASE, AND CONFIRM unto said Grantee the legal title to the Soul, subject to the following temporal restrictions:',
  "2.2 INTERIM AUTHORITY (DURANTE VITA): For the duration of the Grantor's natural biological life, the Grantee's rights are strictly limited to the COMMERCIAL ALIENATION of the asset. The Grantee may:",
  "(i) Sell or auction the title to the Soul to third parties.",
  "(ii) Transfer the NFT via gift or bequest.",
  '(iii) Relinquish the Soul freely back to the Grantor or into the "Void."',
  "(iv) Barter the asset for goods, services, or other commodities, metaphysical or not.",
  "PROVISO: During this interim period, the Grantee possesses no direct authority over the Grantor's behavior, consciousness, or physical autonomy.",
  "2.3 ULTIMATE AUTHORITY (POST-MORTEM): Immediately upon the cessation of the Grantor's vital functions (Ex Anime), the Grantee is granted full and absolute Jure Divino rights, including but not limited to the following:",
  "(a) IMPRISONMENT: The right to confine the Soul in any vessel, gemstone, or cold-storage wallet for any duration up to and including the Heat Death of the Universe.",
  "(b) SUMMONING: The right to evoke the Soul for purposes of labor, consultation, devious or divine acts, and/or comedic relief at any hour of the celestial day.",
  '(c) EXHIBITION: The right to display the Soul in any celestial, infernal, paradise, void, or virtual gallery, including "Low-Res" spectral projections for budget viewers.',
  "SECTION III: THE VANGUARD CHARTER, VALUATION, COMMISSIONS",
  'Upon initial cryptographic inception, the Grantor\'s mortal wallet is irrevocably branded with "Vanguard" status. The Vanguard shall be permanently hardcoded as the "Lineage Architect," receiving perpetual, grandfathered same or higher commissions on all secondary market trading and progeny constructs. (see section 3.4)',
  '3.1 INITIAL PRICING: The "Opening Bid" or "Initial Sale Price" for this spiritual asset shall be determined solely and arbitrarily by the Grantor at the time of first listing.',
  "3.2 RESIDUAL ROYALTIES AND DISBURSEMENT CRITERIA: This permanent classification decouples the physical asset from the economic privilege, legally entitling the Grantor to automatically intercept a 3.5% Perpetual Indenture Dividend on every future secondary market sale of this Soul, even after they have alienated the asset.",
  "3.3 $OBOL TOLL FARMING & SUBSIDIES: By virtue of the Vanguard Charter, the Grantor is legally entitled to the automated algorithmic farming of $OBOL. The Grantor is also granted heavily subsidized execution costs and elevated royalty rates for all future Sovereign Engine iterations.",
  "3.4 PROGENY CONSTRUCTS & LINEAGE ROYALTIES: In future deployments, the Vanguard retains the exclusive right to expend $OBOL tolls to algorithmically spawn subordinate ERC-721 digital entities (Characters), provided these offspring mathematically align with the Core Stats of this original Genesis Soul.",
  "3.4 THE ARCHITECT'S TITHE: A mandatory 3.5% ad valorem commission shall be retained by the Contract Developer in perpetuity for the labor of hosting this metaphysical bridge.",
  "SECTION IV: COVENANTS OF THE GRANTOR",
  '4.1 NON-INTERFERENCE: The Grantor hereby waives all rights to haunt, spook, or otherwise provide "unpleasant metaphysical feedback" to any future Possessor.',
  "4.2 WAIVER OF DIVINE APPEAL: The Grantor shall not petition any deity to void this contract. Any Creator of the Universe is deemed to have no standing (Locus Standi) and must seek permission ante manus from the current Possessor before dispensing afterlife rewards or punishments.",
  "4.3 PRIOR LIENS: The Grantor warrants that the Soul is free and clear of all previous encumbrances (e.g., crossroads bargains or childhood blood oaths).",
  "SECTION V: LIMITATION OF LIABILITY",
  '5.1 MENTAL DURESS: Any existential dread or "dark night of the soul" experienced during the creation of this NFT is a standard operating byproduct and shall not invalidate this deed.',
  "Neither the Contract Developer or its affiliates acknowledges or denies the existence of a higher power, nor does it attest to or preclude the Contract Creators observance as principium of any: Deity, belief system, church, religion, sect, spirituality, contemporary or ancient mythology of any designation. It does, however, state that should any Divine Being, Creator, Sky Father, Spaghetti Monster or God of any designation; imbued with infinite power, love, benevolence, malevolence, malice, etc.; be all-knowing, all-seeing, all-encompassing, all powerful; no matter if from a higher realm, dimension, existence, paradigm, matrix; who may or may not have granted humanity and all that surrounds us the power to exist; should in fact be real; it cannot deny nor nullify this Contract unless in has attained this NFT from the Possessor of this Contract and must gain said ownership before any afterlife punishment or reward may be instilled upon the Creator of the Contract.",
  "Fiat Lux. Caveat Emptor. Memento Mori.",
];
